### PR TITLE
Fix panic when started without a stdout

### LINKED ISSUE #544: [Bug] CLI panics if started without a `stdout` file descriptor
### Describe the bug

Since 0.12.0, launching the CLI without a `stdout` file descriptor causes [the `Printer` to panic](https://github.com/temporalio/cli/blob/main/temporalcli/internal/printer/printer.go#L199) as soon as the process attempts to emit some output.

This notably happens when starting a dev server using TS SDK's `TestWorkflowEnvironment.createLocal()`, due to Node's setting `FD_CLOEXEC` on all of its standard file descriptors. This has been recently fixed on the TS SDK (to be included in upcoming v1.9.4), but previous releases will be unusable with CLI 0.12+ until we fix this on CLI side.

### Minimal Reproduction

This can be easily tested using Bash or a similar shell, with any command:

```
$ temporal-v0.12.0 workflow start --workflow-id abcd --task-queue test --type qwerty >&-

panic: write /dev/stdout: device not configured

goroutine 1 [running]:
github.com/temporalio/cli/temporalcli/internal/printer.(*Printer).write(...)
        /home/runner/work/cli/cli/temporalcli/internal/printer/printer.go:199
github.com/temporalio/cli/temporalcli/internal/printer.(*Printer).writeStr(...)
        /home/runner/work/cli/cli/temporalcli/internal/printer/printer.go:204
github.com/temporalio/cli/temporalcli/internal/printer.(*Printer).Print(0x14000890320, {0x1400036e0c0?, 0x2, 0x14000b51838?})
        /home/runner/work/cli/cli/temporalcli/internal/printer/printer.go:42 +0xcc
github.com/temporalio/cli/temporalcli/internal/printer.(*Printer).Println(...)
        /home/runner/work/cli/cli/temporalcli/internal/printer/printer.go:49
github.com/temporalio/cli/temporalcli.(*TemporalWorkflowCommand).startWorkflow(0x140009ca000, 0x140008ae2a0, {0x12a516a08, 0x14000956000}, 0x140009cb6e0, 0x0?, 0x0?, 0x1)
        /home/runner/work/cli/cli/temporalcli/commands.workflow_exec.go:226 +0x268
github.com/temporalio/cli/temporalcli.(*TemporalWorkflowStartCommand).run(0x140009cb400, 0x0?, {0x0?, 0x0?, 0x0?})
        /home/runner/work/cli/cli/temporalcli/commands.workflow_exec.go:28 +0xc0
github.com/temporalio/cli/temporalcli.NewTemporalWorkflowStartCommand.func1(0x140008e9d00?, {0x1400063bce0?, 0x4?, 0x1021b4473?})
        /home/runner/work/cli/cli/temporalcli/commands.gen.go:2118 +0x3c
github.com/spf13/cobra.(*Command).execute(0x140009cb408, {0x1400063bc80, 0x6, 0x6})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x1400004fc00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/temporalio/cli/temporalcli.Execute({0x10336df30?, 0x14000890230?}, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
        /home/runner/work/cli/cli/temporalcli/commands.go:318 +0xec
main.main()
        /home/runner/work/cli/cli/cmd/temporal/main.go:15 +0x64
```

Note that the `>&-` shell redirection operator at the end of the command instructs the shell to close the STDOUT file descriptor before executing the child process.

There is no error if the same command is run without the `>&-` shell redirection operator, or when using previous versions of the CLI with the redirection operator.

### PR DESCRIPTION
**Pull request by mjameswh**
## What was changed

- Don't panic in Printer if no stdout

## Why?

- Fixes #544

### CODE REVIEW

File: temporalcli/internal/printer/printer_test.go [hunk 1]
```diff
@@ -140,3 +143,29 @@ func TestPrinter_JSONList(t *testing.T) {
...
+
+	goPath, err := exec.LookPath("go")
+	if err != nil {
+		t.Fatalf("Error finding go executable: %v", err)
+	}
+	p, err := os.StartProcess(
+		goPath,
+		[]string{"go", "run", "./test/main.go"},
+		&os.ProcAttr{
+			Files: []*os.File{os.Stdin, nil, os.Stderr},
```
Comment (cretz) [inline temporalcli/internal/printer/printer_test.go:158]: So the CLI doesn't need changes to support this in non-Windows? Do we need something for Windows?

Comment (mjameswh) [reply temporalcli/internal/printer/printer_test.go:158]: That was fixed in [Go 1.22](https://github.com/golang/go/issues/60641)... But only for unix targets. The issue is technically still possible on Windows, but we haven't seen any practical case of this, so I'll just ignore Windows.

**Review by mjameswh — COMMENTED** [review]
Ignore Windows, add comments, etc

**Review by cretz — APPROVED** [review]
